### ISSUE TITLE
Box<Error> with try not implemented?

### ISSUE THREAD

**Issue by jaroslaw-weber** [Aaronepower/ddg#1]
I was trying to do something like this:
pub fn get_related(search_query: &str) -> Result<Vec<RelatedTopic>, Box<Error>> {
    let query: Query = Query::new(search_query, APP_NAME).no_html();
    let results: Response = query.execute()?;
    let related = results.related_topics;
    Ok(related)

}
But cant because there is no conversion to Box error. I think it would be nice to have it implemented. Here is the error:

error[E0277]: the trait bound `ddg::query::Error: std::error::Error` is not satisfied
  --> src/web_search.rs:23:29
   |
23 |     let results: Response = query.execute()?;
   |                             ^^^^^^^^^^^^^^^^ the trait `std::error::Error` is not implemented for `ddg::query::Error`
   |
   = note: required because of the requirements on the impl of `std::convert::From<ddg::query::Error>` for `std::boxed::Box<std::error::Error>`
   = note: required by `std::convert::From::from`

**Comment by Aaronepower** [comment]
Thanks for your issue! I've added an `impl std::Error for ddg::Error` in `0.4`.
