### ISSUE TITLE
Response parsing errors

### ISSUE THREAD

**Issue by jaemk** [Aaronepower/ddg#5]
Parsing of the `TopicResult` variant of the `RelatedTopic` enum expects the payload keys to be in a specific order. The ordering of the api response is not consistent. This probably didn't show up in `ci` builds prior to pr #4 because tests in `src/lib.rs` were behind a "reqwest" feature flag which didn't actually exist and wasn't enabled during testing (would have been enabled with `cargo test --features reqwest`)

**Comment by Aaronepower** [comment]
@jaemk Thank you for the issue! This has now been resolved by allowing non specific ordering.
